### ISSUE TITLE
As a user, I want to see summary holdings information so I know if the materials I want are available even if they are not yet cataloged at the item level

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#100]
See discussion in Jira:
https://wush.net/jira/hathitrust/browse/WS-2977

The required data is contained in the holdings data supplied by API

- [x] @varnum Gather specs for how to access these items 
- [x] @Treevore Design for holdings information
- [x] @bertrama Confirm data are available to UI
- [x] @jonearley Add field to UI.

**Comment by bertrama** [comment]
Needs to have information on the preferred method of how to actually get the darn thing.  Someone said email, but no one said where.  In the current setup, as Ken pointed out it looks like the info is just inconsistent, I recommend considering a design that puts a pseudo-item record in the holdings list for the summary holdings with an action link appropriate.

**Comment by bertrama** [comment]
## Suggestion: 
Move the milestone to Launch.

## Reason: 
It's much too late in the development cycle to take on a new tasks with incomplete specifications.

**Comment by varnum** [comment]
Summary holdings are in the specification for medium and full view catalog records, admittedly without a description of where they come from:

> List of available holdings (866, 867, and 868). Recommend these be collapsed options 
> with the possibility to expand for more detail. (e.g., “Library has: 1:1-23; 2:1-11, 13-133, 
> 135-258 : 1883-1992 : 3-22; 1-278 : 1884-1997 : 105-274 : 1947-1996 : 85-112 : 1937-1950 :
> 2 : 18”)

This comes from holdings API, and is in the holdings record in Aleph. The data there, if available, should be displayed verbatim.

**Comment by jonearley** [comment]
![localhost-3000-catalog-record-000637051 1](https://user-images.githubusercontent.com/1678665/30654209-3eb89d5c-9dfb-11e7-8b3d-666f00e062ad.png)

Added holding summaries.

**Comment by jonearley** [comment]
Ready for review, @varnum.

I used the label ("**Library has**: [summary info]") used in Mirlyn.

**Comment by varnum** [comment]
Looks great -- closing.
