### ISSUE TITLE
As a user I want to see format icons associated with the articles datastore in preview, medium and full record views

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#103]
- [x] Update the [New Search Icons and Formats Key](https://tools.lib.umich.edu/confluence/display/LDD/New+Search+Icons+and+Formats+Key)  in Confluence to show) documentation in Confluence to show Icons associated with individual datastores: Catalog, Articles, Online Journals, Databases and Library Website.

- [ ] Integrate icons from [Articles Icons and Formats Key.pdf](https://github.com/mlibrary/search/files/1315902/Articles.Icons.and.Formats.Key.pdf)
 

- [ ] @jonearley Update Articles Formats to show associated icons.

**Comment by bnhowell** [comment]
Looks like the Articles Icons have already been incorporated tot he New Search Icons and Formats Key. I'm not sure why icons are not appearing in the Articles datastore. 

We do need to associate icons with the library website datastore content types. I've created a key with proposed icons for website datastore types:
[Library Website Icons and Formats Key Copy.pdf](https://github.com/mlibrary/search/files/1319111/Library.Website.Icons.and.Formats.Key.Copy.pdf)

Please give feedback by EOD tomorrow and I'll put these icons into the Confluence page.

**Comment by varnum** [comment]
I like the ones you've selected; I wouldn't swap any of the alternatives for the ones in the box.

**Comment by bnhowell** [comment]
Updated the [New Search Icons and Formats Key in Confluence](https://tools.lib.umich.edu/confluence/display/LDD/New+Search+Icons+and+Formats+Key) to include icons for Library Website datastore content types.


- Blog Post  ![image](https://user-images.githubusercontent.com/16804543/30671595-d445ac86-9e35-11e7-8b9e-42068d21330d.png)
- People  ![image](https://user-images.githubusercontent.com/16804543/30671619-e76c9676-9e35-11e7-87b4-ecab5f11899a.png)
- Research Guides  ![image](https://user-images.githubusercontent.com/16804543/30671629-f0c601da-9e35-11e7-9176-432b13879759.png)
- Exhibits and Events  ![image](https://user-images.githubusercontent.com/16804543/30671632-fa3f603a-9e35-11e7-8b86-431fa7123aed.png)
- Website ![image](https://user-images.githubusercontent.com/16804543/30671639-000c630a-9e36-11e7-9fed-c8614a83e975.png)

**Comment by varnum** [comment]
I think this is ready to implement, so adding the label.

Ken

**Comment by bnhowell** [comment]
I can create a seperwte issue for library website icons if necessary.

**Comment by varnum** [comment]
Please do, @bnhowell .

**Comment by varnum** [comment]
@bnhowell -- Please verify that the articles icons are correct in the live interface at https://search-staging.www.lib.umich.edu/articles  and if so, close this issue.

**Comment by bertrama** [comment]
Copied over to SEARCH-5.
