### ISSUE TITLE
As an advanced user, I want to toggle filter options.

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#107]
Implement advanced search checkbox widget.

**Design**

<img width="402" alt="screen shot 2017-09-20 at 3 22 40 pm" src="https://user-images.githubusercontent.com/1678665/30663115-9d046af0-9e17-11e7-9a0e-2f23c4ab4a5e.png">

https://projects.invisionapp.com/d/main#/console/9866766/234703677/preview

**Tasks**
- [x] @jonearley Add checkboxes
- [x] @bertrama Add value mapping

**Comment by varnum** [comment]
See #23

**Comment by jonearley** [comment]
Implemented advanced search UI checkboxes following these requirements: https://tools.lib.umich.edu/confluence/display/LDD/Filter+Requirements


| Datastore | Label | UID | Type |
| -- | -- | -- | -- |
| Mirlyn | Available online | available_online | Checkbox |
| Mirlyn | Include search only HathiTrust Materials | search_only | Checkbox |
| ArticlesPlus | Limit to articles from scholarly journals | is_scholarly | Checkbox |
| ArticlesPlus | Exclude newspaper articles | format | Checkbox |
| ArticlesPlus | Limit to articles with full text online | available_online | Checkbox | 
| ArticlesPlus | Add results beyond this library's holdings | holdings_only | Checkbox |

**Comment by bertrama** [comment]
Done.
