### ISSUE TITLE
As a user I want to see 'type' icons associated with the library website datastore records in preview, medium and full record views

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#108]
- [x] Update the New Search Icons and Formats Key in Confluence to show icons associated with individual datastores: Catalog, Articles, Online Journals, Databases and Library Website.

- [x] Integrate icons from [Library Website Icons and Type Key.pdf](https://github.com/mlibrary/search/files/1322041/Library.Website.Icons.and.Type.Key.pdf)

- [ ] @jonearley Update Library Website datastore types field (in records) to show associated icons.

**Comment by bertrama** [comment]
Moved to SEARCH-53.
