### ISSUE TITLE
As an advanced user, I want to know all the details of serials holdings

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#109]
**Details**
Add to full description in catalog:

-    310 CURRENT PUBLICATION FREQUENCY.  Label:  Current Publication Frequency
-    321 FORMER PUBLICATION FREQUENCY. Label: Former Publication Frequency
-    515 NUMBERING PECULIARITIES NOTE. Label: Publishing Peculiarities
-    555 CUMULATIVE INDEX/FINDING AIDS NOTE. Label: Cumulative Index/Finding Aids Note

Change the existing field label for the 362 to Former Publication Frequency
**Evidence**
This was put into production in regular Mirlyn today, according to Tim: https://mlit.slack.com/archives/C0MEBMV0B/p1506022759000030 

See https://wush.net/jira/hathitrust/browse/WS-3260

- [ ] @bertrama Make sure fields are available to UI
- [ ] @jonearley Make sure fields appear in UI

**Comment by varnum** [comment]
Do we need anything else for this?

**Comment by bertrama** [comment]
Who's the stakeholder who asked for this change?
What's the need it addresses?
How large is the population with this need?
What would people with this need do otherwise?
How did we determine that the proposed change meets the need that was identified?
What are the possible adverse effects to other needs that operate in the same space?
What's the magnitude of the adverse effects introduced by making these changes? 
How big is the population who is adversely affected?
Is the benefit worth the cost?
When do we reevaluate everything above this?

**Comment by varnum** [comment]
According to Systems, the request put in place in current Mirlyn was a request from Oksana.  When Systems investigated, they discovered that the fields in question were already displaying in Classic and since at some point in the past, Systems was directed to have the same note fields display in the Mirlyn description tag as in Classic, they went ahead and added them.

For a researcher needing to find previous and subsequent copies of a journal -- with all the variance in spelling and naming that took place especially before the 20th century -- these note fields are important for researchers to conduct their research. And, this matches existing policy (corrects an oversight in current Mirlyn).

**Comment by bertrama** [comment]
I'll start filling these in, there are still questions that I think should be answered beyond what's here and what was said in the stand up.

Separate from that, what policy are you talking about?  There's no mention of it in our charge, and it wasn't mentioned when we talked about fields for the catalog, so I'm skeptical that it should apply to our work.

**Comment by bertrama** [comment]
Other information the stakeholder should provide to inform the decision above:
- [ ] Number of records 1 or more instances of the specified field
- [ ] Descriptive statistics of the field for those records with the specified field. i.e. (min, max, mean, median, mode, standard deviation)
    - [ ] Number of times the field appears
    - [ ] Number of characters appearing in the rendered field
- [ ] Number of questions per unit time for Ask a Librarian and/or their particular support staff that could be obviated by the field's presence.

**Comment by bertrama** [comment]
Should we accept any of these, we additionally will need the stakeholder to supply:

A list of records and their expected output for any edge cases that the stakeholder is interested in the display being correct for.  Things to consider:
- [ ] Really short field values.
- [ ] Really long field values.
- [ ] Records with multiple fields of this type.
- [ ] Every combination of subfield that the stakeholder cares about.

**Comment by bertrama** [comment]
Added as SEARCH-54.
