### ISSUE TITLE
As a mobile user I want to see Catalog and Articles filters default closed so I can swipe down and see my search results more quickly and efficiently. 

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#111]
Here's a rough prototype for expanding/contracting catalog datastore filter section in Invision:
https://invis.io/M29P6AYWJ#/254794330_Mobile_Search_Results_Accordian_-Closed-Default-

Catalog and Articles have the most filters. The collapse/expand for Online Journals, Databases and Library Website are not as necessary because they are already so short. 

Technically if they all must have the option then that's fine but it is most needed in Catalog and Articles datastores.

**Comment by bertrama** [comment]
Added as SEARCH-55.
