### ISSUE TITLE
Regression: Filter count limits were removed globally

### ISSUE THREAD

**Issue by bertrama** [mlibrary/search#112]
Filter value counts were increased so that they'd be available to Advanced search, but there isn't a separate control for regular requests.

Tasks
- [ ] @bertrama Add a way to temporarily increase the limit while fetching the initial filters.

**Comment by jonearley** [comment]
Good to know. I noticed a performance drop recently. It is likely all the new React reconciliations. #110

**Comment by jonearley** [comment]
I've improved how I store filters used in search results. For now I've limited those to 50. I'm fine with that being the solution and closing this issue.

**Comment by bertrama** [comment]
It's a performance problem with communication with solr to keep a high facet limit for every request.  I've got an update prepared that'll reinstate the 20-limit for solr after the initial request goes out with 500.
