### ISSUE TITLE
Make custom designed checkboxes accessible.

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#113]
- [x] Add `tabindex="0"` to custom checkboxes.
- [x] Add keyboard support; on enter or space bar toggle checkbox state.

**Comment by varnum** [comment]
On both https://earleyj-drupal8.www.lib.umich.edu/catalog/advanced and https://earleyj-drupal8.www.lib.umich.edu/articles/advanced, I can't tab to the "Access Options" section.

**Comment by jonearley** [comment]
@varnum whoops. That label shouldn't have been added. I haven't begun fixing this issue yet.

**Comment by jonearley** [comment]
Added keyboard support.
