### ISSUE TITLE
Data from 974 $z not appearing in holdings

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#115]
On this record -- https://earleyj-drupal8.www.lib.umich.edu/catalog/record/004671542 -- the  volume/issue information in the 974 $z is not being displayed as it is for other serials. This makes the Request This buttons indistinguishable from each other.

**Comment by varnum** [comment]
See https://wush.net/jira/hathitrust/browse/WS-3260 for feedback (ignoring the notes fields discussion that takes up most of this Jira issue)

**Comment by jonearley** [comment]
![earleyj-drupal8 www lib umich edu-catalog-record-004671542](https://user-images.githubusercontent.com/1678665/30872684-e85fd1a6-a2b8-11e7-935b-9b422a2d69fb.png)

Fixed.
