### ISSUE TITLE
As a user I want to perceive and operate checkboxes in the Catalog and Articles Datastores

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#116]
- [ ] For checkbox elements in Catalog and Articles 'Filter your search' sections, use role="checkbox"  for those element to also have a aria-checked attribute to expose the checkbox's state to assistive technology. 

Example 1: Adding the checkbox role in ARIA

>role="checkbox" aria-checked="false" tabindex="0" id="chk1"></span>
<label for="chk1">Remember my preferences</label><span

**Comment by jonearley** [comment]
Please search for similar issues before creating new ones. This is a repeat of #113.
