### ISSUE TITLE
Search query doesn't update when back button is clicked

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#121]
If you do a search (e.g, for "trees"), see results, then change the search query (e.g., to "flowers") and conduct that search, if you click the back button, you get results for "trees" but the query in the search box remains "flowers" .

- [x] @jonearley Fix and add to staging.
- [x] @varnum Review fix.
- [x] @jonearley When approved, release to production.

**Comment by jonearley** [comment]
Hi, @varnum. Please try the fix found on staging: https://search-staging.www.lib.umich.edu/. When approved I'll release to production.

**Comment by varnum** [comment]
I've tested all sorts of permutations of changing search query along with datastore and filters; the back button is working well. Ready for release. @jonearley

**Comment by bertrama** [comment]
Released a new version to production this morning.  Confirmed the updated behavior is present.
