### ISSUE TITLE
Update Library Website landing page text to include people

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#124]
Change landing page text on to read (new text in bold for clarity here, but not for interface):

Your results will include website pages, research guides, **library staff,** events, exhibits, news, and more.

Heidi noted that we wrote that text when there was still a People datastore, which we have since consolidated into website.

**Comment by jonearley** [comment]
Added.

Preview:
https://search-staging.www.lib.umich.edu/librarywebsite

![screenshot-earleyj-drupal8 www lib umich edu 2017-10-19 14-15-42-908](https://user-images.githubusercontent.com/1678665/31786933-18b6448a-b4d8-11e7-9c02-110df2beeabf.png)

**Comment by varnum** [comment]
Thanks.
