### ISSUE TITLE
Access icons or descriptive labels needed for database records

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#128]
In the spec for databases, https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.myun0nom11, an access icon for databases is required. This could be an icon or a more meaningful text phrase than is currently shown (e.g., authorized-plus-guests).

**Comment by bertrama** [comment]
Added as SEARCH-62.
