### ISSUE TITLE
People results in medium website view don't match spec

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#129]
The spec notes these fields (italicized are not yet implemneted):

- Name
- Type: Staff Directory/People
_- Profile picture
- Working Title
- Department
- Email address
- Phone number
- Office_

https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#

- [ ] @Treevore & @bnhowell -- Provide final designs
- [ ] @jonearley -- Implement designs

**Comment by bertrama** [comment]
Added as SEARCH-64.
