### ISSUE TITLE
Staging search when loading to root sometimes doesn't load fully?

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#130]
![screenshot-search-staging www lib umich edu 2017-10-19 12-43-23-936](https://user-images.githubusercontent.com/1678665/31783130-259d65aa-b4cb-11e7-9e9a-24afa6b510f5.png)

https://search-staging.www.lib.umich.edu/

- [ ] @bertrama Investigate if it could be related to cache. Loading index seems to load a cached (old) version of the site. Where loading a route loads the most recent version.

**Comment by bertrama** [comment]
It's definitely not a caching issue.  I've implemented a work-around though.  I'll call it done for now.
