### ISSUE TITLE
Organize groups of holdings by online first, physical second, other third

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#134]
Update the organization of holdings so that, when present, they appear in this order:

Online
 - Licensed
 - HathiTrust

Physical (alphabetical by location)

Other

Note: put in public beta as low -- if time allows. 

- [x] @bnhowell Provide ordered list of holdings and document this in confluence
- [ ] @jonearley Implement

**Comment by jonearley** [comment]
Updated Ben's task. Visual designs are unnecessary, but a documented ordered list of these so we don't lose the ordering again the future would be better.

**Comment by varnum** [comment]
Documented here: https://tools.lib.umich.edu/confluence/display/LDD/Catalog+Holdings+Order 

Is this OK, @bnhowell ? If so, please check the box at the top of this issue.

**Comment by bnhowell** [comment]
@varnum Just ok'd the order on my end.

**Comment by bertrama** [comment]
Moved to SEARCH-66.
