### ISSUE TITLE
Request This link showing up for holdings type:other

### ISSUE THREAD

**Issue by bertrama** [mlibrary/search#140]
Current behavior:

Holdings record with `type: other` shows a "Request This" call to action.

Desired behavior: 

No call to action on holding records with `type: other`.

Example page [Front-end](https://search-staging.www.lib.umich.edu/catalog/record/009853572).  [Holdings API](https://search-staging.www.lib.umich.edu/spectrum/mirlyn/holdings/009853572).

**Comment by jonearley** [comment]
Thanks for reporting. Fixed.

![screenshot-search-staging www lib umich edu 2017-10-23 10-26-21-231](https://user-images.githubusercontent.com/1678665/31894502-a4854f86-b7dc-11e7-9489-86b5b6fb90b4.png)
