### ISSUE TITLE
Microsites in website search results need a resource type

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#141]
Microsites show up without a 'type', so aren't represented in filters. See, e.g., https://search-staging.www.lib.umich.edu/librarywebsite?query=grenada, in which there are two results, with only one represented in the filter:
<img width="650" alt="screen shot 2017-10-23 at 2 12 49 pm" src="https://user-images.githubusercontent.com/17750831/31905471-48932746-b7fc-11e7-9d59-48ee26591134.png">

**Comment by jonearley** [comment]
This is a feature request, not a bug. Microsites wasn't asked to be a type based on the spec:

**Filters**
- Webpages
- Exhibits and Events
- Blogs and Blog Posts
- Research Guides
- Staff Directory / People

From spec: https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.li2hwr9cky4d

This is a task for @bertrama to make available to the UI.

**Comment by jonearley** [comment]
Does our internal name `microsites` make sense to use as a UI label? Or would `webpages` or something else make more sense here? @heidisb

**Comment by heidisb** [comment]
Nope. Definitely doesn't make sense as a UI label. My assumption is that they would be part of the Website type. They are really an extension of the primary website.

**Comment by varnum** [comment]
Adding them to the "Website" resource type is fine with me.

**Comment by bertrama** [comment]
Moved to SEARCH-75.
