### ISSUE TITLE
In Catalog Advanced search pages, remove library dropdown option for locations with only one library

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#144]
The current Search Beta's catalog advanced search page, The 'Narrow search to' filter section always shows Library, Location, Collections. The location filter is present for libraries with multiple locations as well as libraries with one location leading to duplicate drop-down filters for Bentley Library, Flint Thompson Library, and William L. Clements Library. 

![screen shot 2017-10-25 at 11 44 43 am](https://user-images.githubusercontent.com/16804543/32008336-f6c981e2-b979-11e7-845d-cb24783661ea.png)

@bnhowell recommends that we remove the location filter & drop down for Bentley Library, Flint Thompson Library, and William L. Clements Library. Those libraries would continue to have Library and collection filters & dropdowns. 

![screen shot 2017-10-25 at 11 48 51 am](https://user-images.githubusercontent.com/16804543/32008570-82cab346-b97a-11e7-93e1-fb52acbcb74f.png)

- [ ] @bnhowell Provide designs
- [ ] @jonearley Implement designs

**Comment by bertrama** [comment]
Moved to SEARCH-79.
