### ISSUE TITLE
Use the Flint Ask a Librarian service when the user is scoped to that library.

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#145]
- [ ] @varnum Question: Does FLint want its Ask a Librarian widget used for Flint users?
- [ ] @bnhowell Question: Should the chat widget display with text if you're talking to Ann Arbor or Flint? Will users know how to switch if they're talking to the wrong one? What would that look like? @Treevore 
- [ ] @bertrama Setup presence API proxy for Flint. Similar to: #53
- [ ] @jonearley Have the UI switch to the Flint Ask a Librarian service when the a user selects the flint libraries institution.

**Comment by varnum** [comment]
Occurs to me that there’s a distinction for Ask a Librarian service between users who are identified as Flint by IP or Aleph information and those who scope their search to Flint manually. Do we want the Flint Ask service to be tied to a user-selected Flint scope? Or only by IP address/Aleph?

**Comment by bnhowell** [comment]
@varnum I think we would want the Flit Ask a Librarian service to be tied to IP address/Aleph. The more automated this service can be for the end users the better. Campus scope selection anxiety is real.

**Comment by varnum** [comment]
Makes sense, @bnhowell . I’ll talk with Flint about it and make sure that behavior works for them.

**Comment by bertrama** [comment]
Moved to SEARCH-80.
