### ISSUE TITLE
As a user, I would like to filter catalog results to items held in a particular physical location so that I can find items where I am

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#149]
The specifications asked for a Library filter group (https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.fuj08chbm0eg). We missed it previously. It should be added.

**Comment by bertrama** [comment]
Moved to SEARCH-81.
