### ISSUE TITLE
Copyright info in new library search footer

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#150]
In the footer, update the language of the link to the copyright statement to read “copyright policy” and update the link to be https://www.lib.umich.edu/library-administration/copyright-policy to reflect updates on the library website.

Email from Scott Dennis requesting this change:

Ken, I have been remiss in not passing on this comment that Ana Enriquez sent me week before last about the copyright statement as it's currently appearing in the footer of new library search:

"That looks pretty good to me. We've recently updated the "Library Copyright Statement," and it's now the "Copyright Policy," so I would change that. I would also remove the hyperlink to the Regents page. If people go there with copyright questions, it turns into a bit of a wild goose chase (often ending with an email to us). 

If you wanted to simplify further, you could just put "Copyright Policy," as a link. The Regents' copyright notice isn't required, though that is the proper form if you want to include one (per SPG 601.28)."

Although Ana says it's ok to remove the Regents' copyright notice, I think it's safer to keep it there, so it's crystal clear that the the Library Copyright Policy is not any kind of deviation from the University's standard copyright position.  But I take her point about hotlinking to the Regents webpage not really being helpful in the context of the copyright statement.

To summarize, there are two changes to the footer I'm recommending based on Ana's input:

1) Leave the Regents copyright notice where it is, but don't hotlink it to the Regents webpage.

2) Change the final word in the footer from "Statement" to "Policy" (leaving that hotlink as is--it's linking to the correct page, which has been re-titled "Copyright Policy"), in order to match the new name for the library's official public position on copyright adopted on September 28, 2017.

If you agree, please go ahead and get these changes made; otherwise, let me know.

Thanks!  --Scott

~~~
Scott Dennis
Librarian for Philosophy, General Reference, and Core Electronic Resources
209 Hatcher Graduate Library
University of Michigan
Ann Arbor, MI  48109-1190
Email:   sdenn@umich.edu
Phone:  (734) 647-6484
Fax:      (734) 764-0259
Web:     http://www.lib.umich.edu/users/sdenn
ORCID: 0000-0001-7282-1172

**Comment by bertrama** [comment]
Moved to SEARCH-82.
