### ISSUE TITLE
Hathitrust holding says full text, but is search only

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#22]
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/005639608
https://earleyj-drupal8.www.lib.umich.edu/testapp/spectrum/mirlyn/holdings/005639608

**Comment by varnum** [comment]
See Jira ticket [WS-2894](https://wush.net/jira/hathitrust/browse/WS-2894) for a user report of the same issue.

**Comment by jonearley** [comment]
Resolved.
