### ISSUE TITLE
Update catalog published display format

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#29]
For catalog records, please remove (MARC) from the displayed field label for "Published (MARC)". And when a colon separates city and publisher, there should be a space both before *and* after the colon. So, on https://earleyj-drupal8.www.lib.umich.edu/catalog/record/003082551, the field value should be

```
Milano : F. Angeli,
```
not
```
Milano :F. Angeli,
```

For comparison, see https://mirlyn.lib.umich.edu/Record/003082551

**Comment by bertrama** [comment]
The value provided by Spectrum, and passed on unchanged by Pride is:
```json
[
  ["Milano :", "F. Angeli,"]
]
```
It's pretty much like this everywhere we do marc records.  Did you need those merged for you?

**Comment by varnum** [comment]
Current Mirlyn must process it differently; the space and the colon are
reversed.

**Comment by jonearley** [comment]
Mirlyn might just join these two strings with a space. I could do the same for this field. But should this be a general rule for all fields or specific to just this published field?

**Comment by varnum** [comment]
Gah. That's a question above my pay grade.


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
https://www.lib.umich.edu/users/varnum

**Comment by bertrama** [comment]
In general, what you're seeing is one of two cases.

1. There's a single marc field, with multiple subfields matching the field definition.
    ```json
    [
      ["string1", "string2"]
    ]
    ```
2. More than one marc field, with a single subfield matching the field definition.
    ```json
    [
        ["string 1"],
        ["string 2"]
    ]
    ```

In none of these cases do I expect that the data stored in the marc fields are padded with spaces such that they concatenate cleanly into a displayable string.

In case 2, I probably expect them to appear on separate lines, except for something like Format, which I think we'd normally display on the same line.

**Comment by jonearley** [comment]
@bertrama Let's go with joining case 1 array array items by a space so they are passed to Pride as case 2. I talked with @varnum about this at our check in and he agrees.

**Comment by jonearley** [comment]
Resolved.
