### ISSUE TITLE
Uncaught TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by bertrama** [mlibrary/search#32]
In method [getSorts](https://github.com/mlibrary/search/blob/9bf8ae24d4157d87f3df589620b39a317292f284/src/modules/records/components/Sorts/index.js#L22), the variable `acc` is undefined.  When an expected sort uid is no longer available.

**Comment by jonearley** [comment]
I'm unable to reproduce this bug. How did you get to this error, @bertrama? I added a made up sort uid to the config, but it just ignores it and doesn't error.

**Comment by bertrama** [comment]
I had removed one of the sorting options from spectrum, and this error happened.
