### ISSUE TITLE
Need to include 'Citation only (no full text)' text near 'Read Article' Button in Articles Datastore Records (Medium view records and Full Record page)

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#33]
The 'MGet It' button gives additional context about the record it links to with either 'Full Text Online' or 'Citation only (no full text)' messages as part of the button. This explanatory text appears in the 'MGet It' buttons label text in search result pages and full record pages. (See example below of full record page)

![screencapture-lib-umich-edu-articles-details-fetch-logical-a18798-66157917a5068ecb385dcf0aaa0b83ad13dc75cc629c6cf5e32a5abec04227a82-1502205411074](https://user-images.githubusercontent.com/16804543/29079428-2498ff30-7c2b-11e7-8875-d022674b2433.png)

The same record in the Search Beta does not have the accompanying text. (See Below) Could we include the 'Citation only (no full text)' message to the side or below the 'Go to Item' button link?

![no full text in search beta](https://user-images.githubusercontent.com/16804543/29079983-a18d07d8-7c2c-11e7-9f9a-d83428f10734.png)

**Comment by jonearley** [comment]
@bnhowell It's not there, because it's not [in the spec](https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.d0gtofz61j1c). @varnum and team, should @bertrama and I work on adding this and if yes, for what milestone?

**Comment by varnum** [comment]
Yes, that should be restored; I'm with Ben that it's an important piece of information for the user.  I've added this phrase to the spec in all three record views:

Understand if the article is expect to have full text by seeing the appropriate label [Full Text Online] or [Citation Online (no full text online)]

I'm comfortable having this during the beta-to-launch cycle.

**Comment by jonearley** [comment]
@varnum Sounds good. Thanks for bringing this issue up, @bnhowell.

**Comment by bertrama** [comment]
Moved to SEARCH-38.
