### ISSUE TITLE
Holdings Information and text links missing in medium/full record pages

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#34]
1) The medium record (shown below) displays 'request this media item' and 'request this item' text links but they aren't currently linked to anything.

![screen shot 2017-08-08 at 11 42 07 am](https://user-images.githubusercontent.com/16804543/29080770-acae3540-7c2e-11e7-9563-baafcc585d3f.png)
Link to catalog search results with record above: https://earleyj-drupal8.www.lib.umich.edu/catalog?query=Robert+Altman&filter.location=Special+Collections

2) The same 'request this media item' and 'request this item' links (shown in the medium record) do not appear in the corresponding full record page (shown below)
![full record page missing action text links](https://user-images.githubusercontent.com/16804543/29091804-13175636-7c52-11e7-900c-66cbf53566c1.png)
Link to full record shown above: https://earleyj-drupal8.www.lib.umich.edu/catalog/record/005538759?query=Robert+Altman&filter.location=Special+Collections

3) Current Full Record in Mirlyn does not have a request link for the item with a 'Building use only' status but we do have a Request this item link in Search Beta. Is this item really requestable?
It's also not clear how to request the item in the Donald Hall Collection (no call number or identifying info other than the title). (Probably a Special Collections metadata issue)

![mirlyn full record](https://user-images.githubusercontent.com/16804543/29092433-53b64dda-7c54-11e7-82fb-29fd89d16f73.png)

Link to Mirlyn Record: https://mirlyn.lib.umich.edu/Record/005538759/Holdings#tabs

**Comment by jonearley** [comment]
Fixed: Advanced booking and request action items added for special and media holdings. Note: The Donald Hall Collection can't be requested.
