### ISSUE TITLE
<dl> elements must only directly contain properly-ordered <dt> and <dd> groups

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#35]
**Problem**

Axe throws this issue title as an error flagged serious.

Records use a `<dl>` to display fields. React requires a parent container and so `<dt>` and `<dd>` pairs are wrapped in a `<div>`.

**Solutions**

- `div` might be okay to use according to the spec: https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element

- The next version of React (v16) will allow returning arrays from a render. Meaning I won't have to wrap a field `<dt>` and `<dd>` with a `div`.

**Comment by bertrama** [comment]
Moved to SEARCH-41.
