### ISSUE TITLE
Add a footer with Regents copyright statement

### ISSUE THREAD

**Issue by heidisb** [mlibrary/search#41]
Nowhere else really makes sense to have the copyright statement and keep it persistent. Let's do a super minimal footer. Same background as site header. With the text below in white and centered. Break onto two lines after the first sentence on mobile. Footer can evolve in the future if we need to add anything else.

Copyright © 2017 [Regents of the University of Michigan](http://www.regents.umich.edu/). For details and exceptions, see the [Library Copyright Statement](https://www.lib.umich.edu/library-administration/library-copyright-statement).

**Tasks**
- [x] @Treevore Provide final designs with correct copy.
- [x] @jonearley Add to UI.
- [x] @varnum Review.

**Comment by bnhowell** [comment]
Footer (Desktop) design
![footer](https://user-images.githubusercontent.com/16804543/29941427-8c3f2eba-8e60-11e7-9b88-9706f643510a.png)

Footer (Mobile) design
![mobile footer](https://user-images.githubusercontent.com/16804543/29941434-92f7d1b2-8e60-11e7-8ef0-083e7d546830.png)

**Comment by heidisb** [comment]
This is lovely -- albeit unnecessary at this juncture. We don't have any Help content to link to (and maybe we won't have any at all). I know you're trying to make consistent footers across interfaces @bnhowell, but we can't have a link to nothing/for no reason.

**Comment by varnum** [comment]
What does "Home" do in the footer? There are link to the top of the search site and library main page in the upper left. Does this go to the U-M front page, library front page (www.lib.umich.edu), or search front page (everything search)?

**Comment by Treevore** [comment]
Do we need "Copyright" along with the symbol? Here's a centered option without a "home" button though I think the exclusion of the home button doesn't help much. I would assume the "home" button goes to a search home, whatever that looks like (a search landing page, or blank search page)

![footer 1](https://user-images.githubusercontent.com/502199/29978713-549133f4-8f10-11e7-90c3-aab9fdee6c20.png)

**Comment by heidisb** [comment]
I was going by what was listed in the functional requirements. The public
website only has the symbol, so I would think that's fine.

---
Heidi Steiner Burkhardt | User Experience Specialist | University of
Michigan Library
heidisb@umich.edu | 734.615.6130 | @heidi_sb

**Comment by jonearley** [comment]
Added tasks.

**Comment by jonearley** [comment]
Added footer with text content. I'll need to add the copyright symbol once I can generate it. If @bnhowell or @Treevore want to export that as an SVG from Sketch and then share that here (host on Drive?) I can then add it.

**Comment by varnum** [comment]
&copyright; won't cut it?

**Comment by jonearley** [comment]
It would. You're right. I've been thinking of SVGs too much lately..

**Comment by jonearley** [comment]
Added icon.
