### ISSUE TITLE
Advanced Search -- Fielded Search

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#44]
Bring advanced search fielded search fields up to current with the specification.

- [x] #72 
- [x] #73

**Comment by jonearley** [comment]
https://tools.lib.umich.edu/confluence/display/LDD/Fielded+Search+Requirements

**Comment by jonearley** [comment]
I've added all the spec'd field uids to the search config (#d52aec1c96fbd27d11df54c6cca4a3e2cc63134f) so when those are made available to the UI they will be displayed as options.

**Comment by bertrama** [comment]
Added tasks for sub-issues.

**Comment by varnum** [comment]
@jonearley -- https://tools.lib.umich.edu/confluence/display/LDD/Fielded+Search+Requirements says that Title Starts With is available to the UI for databases and journals.

**Comment by jonearley** [comment]
#72 and #73 are under review.

**Comment by varnum** [comment]
#72 and #73 are done. Closing this one, too.
