### ISSUE TITLE
Institution Filter is Persistent

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#48]
From [the spec](https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.gje644y42s82) :

Some libraries that contribute their catalog records to Mirlyn have searches that are scoped to them: Flint, Bentley, Clements, and Ann Arbor Libraries. Selecting one of these libraries, or accessing from a defined IP address, has the following effects:

**Bentley**
Searches are restricted to Bentley Historical Library (inst=bentley)

**Clements**
Searches are restricted to Clements Historical Library (inst=clements)

**Ann Arbor Libraries**
All Ann Arbor libraries (U-M Library, Bentley, and Clements) (inst=aa)

**Flint**
Searches are restricted to Flint’s holdings (inst=flint). Also:

For each URL found in a bibliographic record 856 field (with indicators that it's the resource itself rather than ancillary material) one of three things can happen:

1. If there's already a proxy prefix in the record url, it is used without change.
2. If the Flint library is selected, or access is from an IP address known to be on the Flint campus, or the user is logged in and has a primary affiliation with the Flint campus, then the Flint proxy prefix (http://libproxy.umflint.edu:2048/login?url=) is prepended to the record url.
3. Otherwise, the Ann Arbor proxy prefix is prepended to the record url.

Ask a Librarian link goes to Flint’s service, http://libguides.umflint.edu/ask

This filter should be sticky for an entire user’s session, unless changed.

**Comment by varnum** [comment]
Not sure this needs a design in itself; once the filter is selected, it doesn't de-select itself until the user removes it.

**Comment by jonearley** [comment]
I confused this issue with #49, but I see now those are separate tasks.

**Comment by jonearley** [comment]
I folded this issue into #49.
