### ISSUE TITLE
Quoted searches not behaving as expected

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#52]
A quoted phrase in new search brings up results that do not include the quoted phrase verbatim. 

For example, the quoted search **franchise history** brings up the following numbers of results in Catalog and Articles, compared to Mirlyn and Articles Plus:

Catalog
[Search Beta](https://earleyj-drupal8.www.lib.umich.edu/catalog?query=%22franchise+history%22): 526
[Mirlyn](https://mirlyn.lib.umich.edu/Search/Home?checkspelling=true&inst=aa&showsearchonly=false&oft=false&lookfor=%22franchise+history%22&type=all&submit=Find&use_dismax=1): 4

Articles
[Search Beta](https://earleyj-drupal8.www.lib.umich.edu/articlesplus?query=%22franchise+history%22): 1,423,891
[ArticlesPlus](https://www.lib.umich.edu/articles/search?kw=%22franchise%20history%22): 246,871

**Comment by bertrama** [comment]
Fixed in the latest cut of pride.
