### ISSUE TITLE
Update website sort option labels

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#55]
Implement these sorting options:

1. Creation Date (Newest First) _Change label from "Date (Newest First)"_
2. Creation Date (Oldest First) _Change label from "Date (Oldest First)"_
3. Title (A-Z) _Page title (A-Z)_
4. Title (Z-A) _Page title (Z-A)_

Items 1 and 2 require a label change.
Items 3 and 4 are already present.

**Comment by jonearley** [comment]
@bertrama If you update the names, but keep the UIDs the same this will be updated in the UI. Let me know if I need to change any UIDs.

**Comment by bertrama** [comment]
Done.
