### ISSUE TITLE
Catalog - Preview View - Published Date missing from interface

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#56]
Published Date for catalog materials is supposed to visible in preview view for the catalog

https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.y5l577grhs3y

**Comment by jonearley** [comment]
It seems the published_date field isn't being passed to records anymore. I wrote a message to @bertrama on [the confluence field spec page.](https://tools.lib.umich.edu/confluence/display/LDD/Field+requirements)

**Comment by jonearley** [comment]
Updated `published_date` to `published_brief`: 24694ade43e1658e75be1a50515eec2d1ada1b2b. Resolved.
