### ISSUE TITLE
Articles -> Format filter not working

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#57]
Selecting a format filter for a format visible in the original results list gives 0 results.

Results list with "Journal Article" format items in it (there are 423 items with format "Journal Article"):
https://earleyj-drupal8.www.lib.umich.edu/articlesplus?query=author%3Atanenhaus

Results list filtered for "Journal Article" items with 0 items:
https://earleyj-drupal8.www.lib.umich.edu/articlesplus?query=author%3Atanenhaus&filter.format=Journal+Article

**Comment by bertrama** [comment]
Fixed.
