### ISSUE TITLE
"Advance Booking" link missing from Askwith items

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#61]
The "Advance Booking" link on Askwith materials is not being displayed. For example, on 
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/003604302

**Comment by jonearley** [comment]
The media holdings access link should be there now.

For the other holding, I did notice the value sent to me for the URL is `null`. @bertrama could you look into fixing this? Related holdings url: http://earleyj.www.lib.umich.edu/testapp/spectrum/mirlyn/holdings/003604302

<img width="906" alt="screen shot 2017-09-05 at 3 25 56 pm" src="https://user-images.githubusercontent.com/1678665/30079546-8b5927fc-924e-11e7-8ef8-c4d14d32f064.png">

**Comment by bertrama** [comment]
Working as intended.  You can't **book/request/get** items in the Donald Hall Collection.

**Comment by jonearley** [comment]
@varnum now knowing this is intended, can this ticket be closed?

**Comment by jonearley** [comment]
If we want to consider a UX solution to records that can't be requested then I think that's a separate design discussion.

**Comment by varnum** [comment]
Nope, this is working as intended. If it circulates, it gets the "request
this media item" link. Building Use Only don't get the link. Close it!


--
Ken Varnum
Senior Program Manager for Discovery, Delivery, and Library Analytics
Library Information Technology | University of Michigan Library
varnum@umich.edu | @varnum | 734-615-3287
https://www.lib.umich.edu/users/varnum
