### ISSUE TITLE
Setup staging and production domains and hosting

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#63]
The two domains to be setup:
- [x] `search-staging.www.lib.umich.edu` for staging.
- [x] `search.lib.umich.edu` for production.

**Sub Tasks**
- [x] @bertrama: Ask A&E to setup these domains and related work.
- [x] @bertrama: Show @jonearley where to place new staging and production code.
- [x] @varnum: When transitioning, update links and or communicate new hosting where necessary.
- [x] @jonearley: Confirm migration from `earleyj-drupal8.www.lib.umich.edu` to new hosting.

**Success criteria**
New search is hosted on both staging and production domains. Staging is behind Cosign authentication and available to library staff. Production is not behind authentication and available to everyone. Both sites are hosted on https.

**Comment by bertrama** [comment]
My notes were for mirlyn-search.lib.umich.edu, did I write the wrong thing @varnum ?

**Comment by jonearley** [comment]
Confirming `search.lib.umich.edu`. I prefer `staging.search.lib.umich.edu` over `search-staging.lib.umich.edu` since I think it is more typical/standard, but whatever is easiest for our environment is fine with me.

**Comment by bertrama** [comment]
`search-staging.www.lib.umich.edu` was more expedient for A&E to implement.

**Comment by jonearley** [comment]
Is there a reason the `www` is necessary?

**Comment by bertrama** [comment]
I have deployment code for `search.lib.umich.edu` prepared.  I've asked A&E about three configuration pieces for the servers and dns that will need to be addressed before everything's ready.

**Comment by varnum** [comment]
Communication plans are in place and/or ready to go.

**Comment by bertrama** [comment]
All configuration needed from A&E is complete as far as I can tell.

**Comment by varnum** [comment]
Thanks @bertrama and @jonearley for making this happen.
