### ISSUE TITLE
Change "Special Holdings" heading in catalog holdings to "Reading Room Use Only"

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#64]
Special Holdings is meaningless. I think we have to have something better for these materials for the beta. Reading Room Use Only is clear and makes sense, as long as there is a commitment to getting the records updated in Aleph. 

Martha is working with Bentley & Clements to get approval to change item status in Aleph for all the materials that would show up in this category to be "Reading Room Use Only". Once approved, that will go to Systems for a bulk change.

**Comment by jonearley** [comment]
Added. Example: https://earleyj-drupal8.www.lib.umich.edu/catalog/record/002741364

<img width="822" alt="screen shot 2017-09-07 at 11 36 47 am" src="https://user-images.githubusercontent.com/1678665/30171768-dca37838-93c0-11e7-8308-41b9cf0e44e3.png">
