### ISSUE TITLE
Update fields for People results in Website datastore

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#67]
Per spec: 

**Preview View**
Fields
- Name
- Type: Staff Directory/People
- Working Title
- Email address

User can
- See contact email for people
- Access more information about people

**Medium View**
Fields
- Name
- Type: Staff Directory/People
- Profile picture
- Working Title
- Department
- Email address
- Phone number
- Office

User can
- See all contact information for people
- Access more information about people
- Access staff profile page on www.lib
- Select and export records
- Email to user

**Comment by bertrama** [comment]
The specs document makes this look like it's a separate datastore, is the issue wrong, or the specs wrong?

**Comment by varnum** [comment]
Like Research Guides, staff directory/people results are subsumed into website results. I'll update the spec later today to make that clearer.

**Comment by varnum** [comment]
See https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.ry9ath3tderh

**Comment by varnum** [comment]
@jonearley How much would it take to update staff directory results to include all the text fields in the Website data store? Is this something that could reasonably be done before public beta? (If we could do photos, great, but the fields specified above would be very helpful.)

**Comment by jonearley** [comment]
@varnum It would take me a few days to configure and test for most fields. Custom fields like pictures would take a little more effort.

Not all fields for the various types (webpage, research guides, blog posts...) are available to the UI yet under the website datastore. We need to still do the work on the backend to merge all these once single datastores into just the website datastore and then have the fields be unique.

@bertrama can better estimate if this could be done for public beta.

**Comment by bertrama** [comment]
Moved to SEARCH-48.
