### ISSUE TITLE
Relabel finding aid buttons to 'View finding aid'

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/search#68]
- Can we relabel the button access finding aids, currently labeled 'Available online', to **'View finding aid'**

- Two headings: 'Online Resources' and 'Holdings (Other)' in the record below are redundant. Why not have a single heading 'Online Resource' with 'View finding aid' button and the location where the items associated with the finding aid can be found. 

- Next to the 'View finding aid button' can we show the Location info (e.g Special Collections Archival and Manuscript Collections) to show where the physical materials referenced in the electronic finding aid live?

![screen shot 2017-09-08 at 10 51 26 am](https://user-images.githubusercontent.com/16804543/30217319-c81e386c-9483-11e7-82da-48a448645a52.png)

record shown above:
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/003084800?query=all_fields%3Afinding+aid&filter.location=Special+Collections&sort=relevance

**Comment by bertrama** [comment]
This looks to me like it's a special case of the situation where a record has an `85642` field.
Many of these records have unclean `$u`, `$y`, `$x`, `$z`, and `$3` fields.

For whatever reasons, our records don't usually have a `$y` and have inconsistent patterns in a `$3` and `$z`, and sometimes they have stuff in the `$u` when it should be in the `$x`.

Putting the work of figuring out what should be shown in between the browser and the search engine is one of the things that makes our interfaces slow and a poor experience for end users.  Thus I advocate against working around bad data.

I recommend the following:
* Links without a `$u` will not be shown.
    * i.e. to suppress a link, move the `$u` into the `$x`.
* Records without a `$y` will show some default link text like `Available online`.
* Records with a `$3` from a controlled vocabulary can be gathered under an appropriately named heading.
    * i.e. `Finding aids`, `Tables of Contents`, `Author's mothers-in-law's websites`, etc.
* Have someone be responsible for keeping these records clean.
    * Do periodic scans for mis-keyed entries.
    * Have a known point of contact for when there are complaints about what's showing where.
* The `$3` should be from a controlled vocabulary.
* The `$z` can be text that's shown next to the link, such as vendor info, authentication requirements.
* Any other information that isn't available in the 856 spec which we need in the front end of the interface to display a specific link should be encoded as json in the `$x`.

**Comment by varnum** [comment]
I think all of what you recommend is eminently sensible, Albert. 

I think points 4-6 require work from Technical Services (which would probably start with Martin Knott & Jon Rothman) to make happen, both to update existing records, and to set new patterns for the future. I'll start that conversation.

**Comment by varnum** [comment]
Waiting on Systems & TS to make these changes to Aleph data so they flow through to the Solr index.

**Comment by bertrama** [comment]
Added as SEARCH-49.
