### ISSUE TITLE
As a catalog user, I want to drill down through decades to years in the filter

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#69]
Comment from Jon Rothman in Slack:

> Has there been any consideration to providing the enhanced date of publication filters 
> we use in Mirlyn? Dates are indexed both individually and by decade. That partially 
> overcomes  the limitations on how many filter values can be displayed - it effectively 
> allows a kind of drill down in many cases.

**Comment by bertrama** [comment]
Added as SEARCH-50.
