### ISSUE TITLE
Remove "Available for Print on Demand" from "Available online" filter group in Catalog

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#70]
Per Jon Rothman:

> The "Available for Print on Demand" filter can be eliminated. That information used to be 
> provided for materials that could be printed via the Espresso Book Machine - it became 
> obsolete when the EBM was retired.
> 

**Tasks**
- [ ] Ask those up stream to remove it.

**Comment by jonearley** [comment]
Removed myself as an assignee. I don't think the UI should be looking for filters and removing them. This should likely happen at the source or up stream.

**Comment by bertrama** [comment]
+1 to removing upstream.

**Comment by varnum** [comment]
Sent this to Jon Rothman:


You'd mentioned in Slack some time ago that we should remove the "Available for Print on Demand" from the "Available Online" filter group in new search.  Albert & Jon have investigated, and think this status is best removed from the data in Solr, rather than once it makes its way into the interface. 

I don't see an analogous filter in current Mirlyn. If I look at the MARC for an item that is findable using this filter, I see what I think causes the filter item to appear, a 973 field. 
`973 |a AP  |b avail_ebm_pod`

Would the correct way to handle removing this filter from the group be to no longer pass this along from Solr to Aleph, or to remove this from the Aleph records entirely? Or something else?

**Comment by varnum** [comment]
Fixed by Tim Prettyman in Aleph.
