### ISSUE TITLE
As a user, I want to enter publication dates in a variety of ways so that I can narrow in on the date or date range I'm looking for

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#74]
The "Published" field in Articles Advanced Search should be changed to the date widget currently in place for the Catalog advanced search so that a user can easily enter start, end, or date ranges for articles.

**Tasks**
- [x] @jonearley Add date range widget to UI
- [x] @bertrama Accept date range widget values: `before2010`, `after2010`, `2010`, `2010to2015`

**Comment by jonearley** [comment]
Added the widget to the UI, although the values are not being used to search yet. Added a task for @bertrama to make this happen.
