### ISSUE TITLE
As a user, I want to be able to see and click on linked titles to access previous, subsequent, and alternative records for a particular holding, so that I can find the right item on the shelf.

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#76]
From original suggestion: I'm concerned that there is no link between records that have ANA LKR fields (e.g., https://mirlyn.lib.umich.edu/Record/007905709 compared to https://earleyj-drupal8.www.lib.umich.edu/catalog/record/007905709 )

**Comment by varnum** [comment]
See also https://earleyj-drupal8.www.lib.umich.edu/catalog/record/000494628

**Comment by bertrama** [comment]
This issue needs details for how to find the `ANA LKR` fields.

**Comment by varnum** [comment]
From Tim:

The linking information is contained in the JSON response from getHoldings.  For the example cited (bib number 007905709), getHoldings returns two "down" links:  http://mirlyn-aleph.lib.umich.edu/cgi-bin/getHoldings.pl?id=007905709.  Included is the bib key and title of the linked record, which is used to build links to the record under the heading "Linked titles".  

Those target records contain "up" links back to the parent record:
http://mirlyn-aleph.lib.umich.edu/cgi-bin/getHoldings.pl?id=007905715
http://mirlyn-aleph.lib.umich.edu/cgi-bin/getHoldings.pl?id=007905728

The generated links in each record are displayed with the heading "Included in".

An example with lots of down linked records is:  https://mirlyn.lib.umich.edu/Record/004759908

**Comment by varnum** [comment]
@Treevore -- does this issue need any designs from your perspective? It refers to serial titles that have changed titles and/or split up, with links from old-to-new, new-to-old. The expedient thing would be turning the already-displayed titles into links. Does anything else need to happen?

**Comment by bertrama** [comment]
Moved to SEARCH-51.
