### ISSUE TITLE
As a user, I want to be able to access all datastore results from an Everything search from the end of the list of results for a datastore, so on a small screen I do not need to scroll up to get to all results

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#77]
From the feedback link: "Also, does the UX allow for a bookend link at the bottom of each card?  "13,001 results" is a hot-link at the top of the card, but I was looking for "more"-type link at the bottom of each card.  Maybe "go to Catalog results" ?"

**Comment by heidisb** [comment]
Didn't we have it in both places originally? Was removing it from the bottom of each card a conscious decision?

**Comment by varnum** [comment]
I think it was in at least some of @Treevore 's designs, but not sure if/when it fell off (and why).

**Comment by jonearley** [comment]
It's not there because people had a way to get to it (by clicking the header). And so this task has been backlogged to work on features with higher priority. It hasn't been forgotten.

**Comment by bertrama** [comment]
Added as SEARCH-46.
