### ISSUE TITLE
As a user who loves opening pages in tabs, I would like better page titles so that I can more easily find the page I opened.

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#78]
**Context**
Page titles are all "Search", with no indication of whether the page is a search interface, a search result list, or a single item. This could be improved for bookmarking and sharing, as well as for browser navigation. And probably would help improve Google/Bing/etc. retrieval to the extent those services crawl pages (such as Databases).

https://wush.net/jira/hathitrust/browse/WS-2893

**Tasks**
- [ ] @jonearley Add page specific titles.

**Template**
[page title][delimiter] [context]
The context is dropped for detail pages.

| Route        | Tab title          |
| ------------- |-------------|
| / | U-M Library Search       |
| /articles      | Articles · U-M Library Search       |
| /articles/advanced      | Articles Advanced Search · U-M Library Search       |
| /catalog?query=parrots | parrots · U-M Library Search       |
| /catalog/record/006533138 | A cargo of parrots... |

**Comment by varnum** [comment]
Needs a template. I suggest:

For searches:
U-M Library Search - <datastore> - search for <query>

For records
U-M Library Search - <datastore> - <item_title>

@bnhowell @heidisb @jonearley -- What do you think?

**Comment by heidisb** [comment]
Yeahh. This is a good area for improvement. I've never really looked at best practices for this sort of thing. <item_title> for full records make sense. I'm not as sure on the search results. Do we need to somehow indicate the datastore page title? How long is too long when including the "search for"? What is actually possible to implement? So many questions?

**Comment by jonearley** [comment]
This is typical practice: [page title] [delimiter] [context]. Sometimes the context is just dropped (like on news/blog sites)

**Some examples**

| Route        | Title           |
| ------------- |:-------------:|
| / | Library Search       |
| /articles      | Articles · Library Search       |
| /catalog?query=parrots | parrots · Library Search       |
| /catalog/record/006533138 | A cargo of parrots... |

**Comment by heidisb** [comment]
Stick with typical practice fo sho. I say.

---
Heidi Steiner Burkhardt | User Experience Specialist | University of
Michigan Library
heidisb@umich.edu | 734.615.6130 | @heidi_sb

**Comment by varnum** [comment]
Can we add "U-M" before "Library Search"? At least, until we get the official name.

**Comment by jonearley** [comment]
Yeah, we can make it "U-M Library Search".

**Comment by jonearley** [comment]
I have the info I need to implement this feature. Updated tags and added tasks.

**Comment by bnhowell** [comment]
+1 for both @jonearley and @varnum suggestions.

**Comment by bertrama** [comment]
Moved to SEARCH-30.
