### ISSUE TITLE
As an advanced user, I would like to be able to select records and export them into common citation formats and tools

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#79]
Maybe I'm missing something, but I don't see an option to see a quick APA
or MLA (or Chicago!) citation from ArticlesPlus in the existing interface or
the new one. I think this would be super valuable. And if it does exist, and I
just can't find it, isn't that just as bad? Can you find a way to make it super
obvious that that feature exists (a la "cite" from Google Scholar)? I didn't
see anything about citations on the "Search Beta Features Status."

See https://wush.net/jira/hathitrust/browse/WS-2870

**Comment by bertrama** [comment]
Captured in SEARCH-27, SEARCH-28.
