### ISSUE TITLE
As a user, I would like to be able to browse list of journals and databases by name or subject

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#80]
Current search tools has an alphabetical and academic-discipline browse function. 

Need to develop specifications for search tools browse-equilvant functionality for journals and databases, likely linked from landing page for those datastores.

**Comment by bnhowell** [comment]
I'll include tasks related to this user story in my next usability test. Curious about user behavior and browse vs. search when looking for name or subject in online journals or databases datastores.

**Comment by bertrama** [comment]
Captured as SEARCH-24, SEARCH-25, SEARCH-26.
