### ISSUE TITLE
As a user, I would like to be able to see U-M Library blog posts in the library website results so that I can access the full scope of library content

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#83]
Currently it seems that blogs are only accessible through site search at the blog level, not at the post level.  The spec has blog post content being indexed: https://docs.google.com/document/d/16e4tU6rPuc--wvToz-JEBnDwckHl9Lm_8sb0PJpceyc/edit#heading=h.ry9ath3tderh

Fields needed in interface:
Page title
Published On date
Brief description

- [ ] @bertrama Add blog  posts to Solr index
- [ ] @Treevore Finalize design for blog post in website results
- [ ] @jonearley Implement designs
- [ ] @varnum Review

**Comment by bertrama** [comment]
Moved to SEARCH-19, SEARCH-20, SEARCH-21, SEARCH-22, SEARCH-23.
