### ISSUE TITLE
As a user, I want to know if a journal series extends to the current issue or not, so that I can access the best source

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#84]
Current holdings displays for serials follow this pattern:
2012 - Access to the OpenEdition journals online version restricted; authentication may be required:

It is unclear if the 2012 is a single year, or the start of range continuing indefinitely.

For serials with no end date in the metadata, add "present" after the hype:
2012 - present Access to the OpenEdition journals online version restricted; authentication may be required:

**Comment by bertrama** [comment]
This is a metadata problem.  What you're seeing is the `856$3` immediately followed by the `856$z`.
