### ISSUE TITLE
As a user who wants a book that is lost, stolen, damaged, or brittle, I want to access the item in HathiTrust so that I may use the item.

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#85]
**Background**
Under Section 108 of U.S. copyright, the library may present a full text digital version to an authorized user in lieu of a physical item that is deemed lost, stolen, damaged, or brittle. In current Mirlyn, an item that meets these characteristics has an additional note in the HathiTrust description that reads (if the user is on-campus): "Full view available to authenticated UM users and in some UM Libraries" with a more link that has a pop-up with additional details. See https://mirlyn.lib.umich.edu/Record/000387706 as an example.

**Determining Section 108 Access**
(From Jon Rothman)

That's also determined on the fly based on a combination of factors: There must be at least one copy in the print holdings data supplied to HathiTrust by UM that indicates it is damaged, lost or stolen, the user must have an IP address which is included in the current list of machines physically in UM Libraries (this used to mean that you could only get the access from wired library workstations, not personal machines on MWireless; there were discussions with ITS about ways to solve that  issue a couple of years back, but I'm not clear whether anything came of it that would be meaningful in this context). Tim can fill in on how it works. Scott D. and/or Kathleen might have more up-to-date information on MWireless IPs and access.

**Comment by bertrama** [comment]
Moved to SEARCH-18.
