### ISSUE TITLE
As a user, I want to know what floor a book is on so that I can easily go get it myself

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#86]
Location information for books in the catalog that are in open-access stacks should include the floor location, based on the lookup table maintained by Operations and implemented in current Mirlyn. Floor information is displayed as part of the location (building, library, floor, call number) displayed for items.

- [x] @varnum Investigate lookup table for collection & call number to produce floor location
- [ ]  @bnhowell and @Treevore -- finalize location design

**Comment by varnum** [comment]
Tim Prettyman said:

> There's also a json config file that's used to add floor locations to the location 
> display, based on call numbers.  It's generated from data in a google sheet that 
> Geoff Stoll maintains, and used when the full record is displayed.  The json file is 
> conf/floor_locations.json, and the code that processes/uses it is in 
> services/Record/RecordUtils.php
>

**Comment by bertrama** [comment]
Moved to SEARCH-16, SEARCH-17.
