### ISSUE TITLE
Should we have a search specific favicon?

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#87]

**Comment by varnum** [comment]
It looks like we don't have one at all for guides.lib.umich.edu or mirlyn.lib.umich.edu, a maize-on-blue block-M on www.lib, and a maize-on-transparent for staff.lib. I'd go with the maize-on-blue one for search.

Any other thoughts, @heidisb @bnhowell @Treevore ?

**Comment by heidisb** [comment]
We used maize-on-blue for Microsites, too. I agree with using that one.

**Comment by varnum** [comment]
Sounds like we've answered this: maize-on-blue block M from www.lib, sites.lib, etc.
