### ISSUE TITLE
As an advanced user, when I change the sort order of a results list, I would like the sorted list to start at page 1 so that I can more efficiently navigate

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#90]
Based on discussion on #54. 

If you change sort options to Author A-Z, move ahead some number of pages (I edited the URL to put myself on page 52), and then change sort options to Author Z-A, you stay on page 52 of the resorted list.

So I started with
https://earleyj-drupal8.www.lib.umich.edu/catalog?query=bananas

Changed sorting
https://earleyj-drupal8.www.lib.umich.edu/catalog?query=bananas&sort=author_asc

Went to next page
https://earleyj-drupal8.www.lib.umich.edu/catalog?query=bananas&page=2&sort=author_asc

Edited URL to go to page 52
https://earleyj-drupal8.www.lib.umich.edu/catalog?query=bananas&page=52&sort=author_asc

Changed sorting
https://earleyj-drupal8.www.lib.umich.edu/catalog?query=bananas&page=52&sort=author_desc

That feels counterintuitive; if I change sort options, I'd expect to go to page 1 of the sorted list.

Ben Howell notes:
> I'd be in favor of resetting page to 1 after a  sort change because as a
> user I want to activate a sort so I can see the best results that match my
> sort request first.

**Comment by bertrama** [comment]
Captured as SEARCH-14, SEARCH-15.
