### ISSUE TITLE
Donor bookplate design may not be optimal

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#91]
See previous ticket, #89, for details. On records on which donor bookplates appear, e.g., https://earleyj-drupal8.www.lib.umich.edu/catalog/record/005867744, the bookplate is rather large.

**Comment by bnhowell** [comment]
The example link above is broken. Here is another example:
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/012631186

As long as the bookplate has proper alternative text (i.e., alt="Decorative bookplate for the Lucius N. Littauer Foundation Judaica Book Fund at the University of Michigan") or provides supporting context nearby (as it nearly does now) about the content of the image, I'm fine with the current size. The image and content would be accessible for those with sight impairments as well as those using screen readers.
 
Here is a screenshot on iPhone 6 representing how it scales well on mobile. 
![screen shot 2017-09-20 at 5 37 34 pm](https://user-images.githubusercontent.com/16804543/30668946-7f1223da-9e2a-11e7-98ef-ac503d5995cd.png)

**Comment by varnum** [comment]
With the addition of alt text (attn: @jonearley) , the current implementation is fine for the beta. We can figure out if there's a better way to present the icon (smaller, perhaps, on full-width displays) for the full launch milestone, where this issue is slated to be addressed.

**Comment by bertrama** [comment]
Captured in SEARCH-10, SEARCH-11, SEARCH-12, SEARCH-13.
