### ISSUE TITLE
We don't use Google Book holdings. Is that an issue?

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#92]
For example:

https://earleyj-drupal8.www.lib.umich.edu/catalog/record/005867744
https://mirlyn.lib.umich.edu/Record/005867744

**Comment by varnum** [comment]
This is is an error; Tim Prettyman says it's a withdrawn item that should have been suppressed in Aleph so not available in the catalog. I'll report it to Tech Services.

In general, we should never see an item with only a Google Book Search holding. Some items might have those an additional holding, but that was past practice and there shouldn't be many. @jonearley

**Comment by jonearley** [comment]
Thanks for the clarification.
