### ISSUE TITLE
Public Beta Feedback Survey

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#93]
Is our current Search Beta feedback survey (designed for library staff) what we want for the campus?

- [x] @varnum Draft survey
- [x] @bnhowell Review survey
- [x] @jonearley Update link in UI to point to new survey when search goes to public beta

**Comment by heidisb** [comment]
Ooooooh I'm not sure. The current feels very targeted towards staff. I don't think we want to be saying things like "website elements, interactions, content, etc." in the public feedback mechanism. The amazing faces can probably stay, but I think we need a different question after that. Are you planning to keep maintaining the roadmap @varnum?

**Comment by varnum** [comment]
Yes, I am planning on keeping a link to a roadmap -- relabeling it as such, and making it more narrative (here are the things we're working on).

**Comment by heidisb** [comment]
Cool. Looking again, I don't think it will require major changes. Am thinking we can remove the e.g. in the parentheses for the second question and it's still clear what we're asking. And I'm not sure whether we still want to ask the third question, that is better answered by @bnhowell for the second option and you for the first @varnum. Do you want to be answering questions from the general public?  

Do we plan to make a copy of the existing survey to start fresh with the beta, or just edit the one we've been using?

**Comment by varnum** [comment]
I created a copy of the existing survey and did some editing on the questions. I shared it with Heidi & Ben for editing; the rest of you should be able to view it:
https://umich.qualtrics.com/ControlPanel/?ClientAction=EditSurvey&Section=SV_9SH992ZSrUoTeIJ&SubSection=&SubSubSection=&PageActionOptions=&TransactionID=2&Repeatable=0

**Comment by varnum** [comment]
@bnhowell -- does the public beta survey look OK to you?

**Comment by bnhowell** [comment]
I like the first and second question. 

I'd remove the third question, I don't think we want to be responding to each question from the general public. (Happy to be enlightened why this would be useful). If this final question was meant to help with usability participant recruitment, I'd say we generally like to handle that recruitment on our own.

**Comment by varnum** [comment]
I'd like to be able to follow up with people who want a response. That's on me to manage. :) I did revise the question slightly to make it more succinct.

**Comment by heidisb** [comment]
Yeeep. I specifically brought up whether or not to keep a version of question three @bnhowell and @varnum wanted to.

*SHIP IT*

**Comment by jonearley** [comment]
Share the survey link here and I'll update it when we launch the public beta.

**Comment by varnum** [comment]
Here it is:
https://umich.qualtrics.com/jfe/form/SV_9SH992ZSrUoTeIJ

**Comment by jonearley** [comment]
Updated to get ready for switching over soon.

**Comment by varnum** [comment]
Looks good. I updated the link in the qualtrics survey to point back to the static roadmap page in  search (at it's future permanent address, search.lib.umich.edu). Good to go.
