### ISSUE TITLE
Are we labeling the institution filter "Institution" or "Library"?

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#94]
I've seen it used in designs as "Library" and in issues as "Institution".

**Comment by heidisb** [comment]
Talked with Ken and we say "Library." It's the least bad option and replicates what is on the current Mirlyn Advanced Search page: https://mirlyn.lib.umich.edu/Search/Advanced. Institution isn't really accurate. Thanks for checking!

**Comment by varnum** [comment]
This is ready for @Treevore to design. Changing to enhancement, @jonearley .

**Comment by varnum** [comment]
@Treevore Do you have final designs for the library (formerly 'institution') filter?

**Comment by jonearley** [comment]
This issue isn't about the entire feature, just the labeling question, @varnum. Seems to be decided as "Library" and not "Institution."

Issue #49 is for the rest of the work.
