### ISSUE TITLE
Ensure support for ES5+ browsers

### ISSUE THREAD

**Issue by jonearley** [mlibrary/search#95]
ES5 browser support is the baseline for search: http://caniuse.com/#feat=es5. A browserstack account is available for help with testing.

**Tasks**
- [ ] Ensure support for ES5+ browsers.
- [ ] Fix or create issues for incompatibilities.

**Comment by bridgetburke** [comment]
I'm working on this. @jonearley, let me know if there are any specific behaviors that are of concern to you.

**Comment by jonearley** [comment]
Try out different page types (bentobox, datastore, full record), but I expect most issues will be  caught on page load rather then specific page types or UI interactions.

**Comment by jonearley** [comment]
ES5+ browser tested and issues resolved: #136
