### ISSUE TITLE
Identity of site for public beta

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#96]
Based on TASC directives, the search tool's identity for the public beta launch should include these items:

- The library's logo (the stacked block-M & phrase "Library")
- The elements "Search", "Mirlyn", and "Beta". "Search" should be the key element. "Mirlyn" can be less prominent, but it needs to be present.

- [x] @jonearley Update interface

**Comment by Treevore** [comment]
![searchlogos1](https://user-images.githubusercontent.com/502199/30663352-5c52d446-9e18-11e7-8f54-e1378228befe.png)

Any of these doing anything for anyone? Wondering if I had the order of words correct.

**Comment by varnum** [comment]
The second two (Search Mirlyn) variants meet the requirements from TASC. Either option works for me.

**Comment by jonearley** [comment]
Either of the two look nice. I prefer the third with the beta as a tag style.

**Comment by varnum** [comment]
I shared these graphics with Scott; he made the following comments, which I agree with, in keeping with TASC's request that we keep the temporary name generic, but include Mirlyn as a cue: "there should either be parentheses around 'Mirlyn', or a slash between 'Search' and 'Mirlyn'--something more than just the difference in text color to suggest that it's a hybrid name, not an imperative phrase where "Search" is the verb and "Mirlyn" is the object of that verb.  That may be uglier and less cohesive, but since it's not intended to be the permanent name and logo, I think that's ok."

**Comment by Treevore** [comment]
![screen shot 2017-09-25 at 2 20 34 pm](https://user-images.githubusercontent.com/502199/30824223-d2199ee8-a1fc-11e7-98f4-d40742288890.png)

Here's a quick mockup with the slash/bar in between.

**Comment by varnum** [comment]
Looks good -- let's get it in the interface when possible.

Ken

**Comment by jonearley** [comment]
@Treevore could you provide the M Library logo as an SVG? Please keep the background transparent and trim so there is no spacing around the logo.

**Comment by jonearley** [comment]
@Treevore Can you add this to Invision so I can pull out colors and spacing more accurately and easier? Thanks!

**Comment by jonearley** [comment]
@Treevore the 'beta' text looks like a new or reintroducing a mono space font. What's the name again? I deleted it from my project after it was removed from the holding column headings.

**Comment by jonearley** [comment]
Site name updated. Preview:

<img width="302" alt="screen shot 2017-10-09 at 2 13 46 pm" src="https://user-images.githubusercontent.com/1678665/31352316-567a2112-acfc-11e7-8a21-aa932b983220.png">

**Comment by jonearley** [comment]
To get this closed, I'm adding ready for review even though I created this one off a PNG mockup and not a final design provided with InVision or Sketch.
