### ISSUE TITLE
Discussion: Should sort label and sorted field label match?

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#97]
In the project team meeting today, there was discussion about whether the "Creation Date" catalog sort fields would make sense. I wondered if the field they sort on, labeled as "Published", should be the same as the sort field. That is, should they both be "Creation Date" or both be "Published".

**Comment by bertrama** [comment]
IMO: No.

The `Published` field is more than just a date. And strictly speaking, we're not sorting on the Published field. i.e. same-year publications aren't sorted by date then city, then publisher.

This is another area where our stakeholders need to be reminded that the audience isn't them, or a vocal minority of faculty.  We value their input, but it should not be used to dictate what the designs are.

**Comment by bertrama** [comment]
## Suggestion: 
Move the milestone to Launch.

## Reason: 
It's much too late in the development cycle to take on a new tasks with incomplete specifications.

**Comment by heidisb** [comment]
This is one where I don't feel like I know enough to chime in. I'm not sure what we changed or what the Created On actually sorts vs what Published does.

**Comment by varnum** [comment]
That was just a thought for discussion. We can leave it as it is.
