### ISSUE TITLE
Catalog preview view showing Get This for non-circulating Donald Hall materials

### ISSUE THREAD

**Issue by varnum** [mlibrary/search#99]
See, for example, items in this results list:
https://earleyj-drupal8.www.lib.umich.edu/catalog?query=pulp+fiction&filter.location=Donald+Hall+Collection

They should show as "Building Use Only" as in the full view:
https://earleyj-drupal8.www.lib.umich.edu/catalog/record/003816953?query=pulp+fiction&filter.location=Donald+Hall+Collection

**Comment by jonearley** [comment]
Fixed.
